name: 'Setup MSVC Developer Command Prompt'
description: 'Sets up a Microsoft Visual C++ tools for command-line usage'
author: TheMrMilchmann
inputs:
  arch:
    description: 'The target architecture'
    required: false
  vs-path:
    description: 'The path to the Visual Studio installation'
    required: false
  export-path-to-vcvarsall:
    description: 'The environment variable to store the path to vcvarsall.bat in'
    required: false
  export-path-to-vs:
    description: 'The environment variable to store the path to the Visual Studio installation in'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: terminal
  color: gray-dark